Planning-Inspectorate/infrastructure-tooling

- .gitignore
- .pre-commit-config.yaml
- .tflint.hcl
- infrastructure/backend.tf
- infrastructure/container-registry.tf
- infrastructure/locals.tf
- infrastructure/provider.tf
- infrastructure/region.tf
- infrastructure/resource-group.tf
- infrastructure/variables.tf
- pipelines/infra-cd.yml
- pipelines/infra-ci.yml
- Adds terraform code for container registry and resource group
- Adds pre-commit hooks for Checkov, tflint, terraform-docs, formatting and validate
- Adds CI and CD pipelines, these are a bit messy at the moment, but at least they work - will look to tidy up later
> Add container registry and pipelines

- pipelines/infra-cd.yml
- pipelines/push-vm-image.yml
> Update pipeline after template changes

- infrastructure/azure-devops-agent-pool.tf
- infrastructure/cloud-shell.tf
- infrastructure/data.tf
- infrastructure/key-vault.tf
- infrastructure/network.tf
- infrastructure/provider.tf
- infrastructure/variables.tf
- packer/azure-agents/build.pkr.hcl
- packer/azure-agents/sources.pkr.hcl
- packer/azure-agents/tools.sh
- packer/azure-agents/variables.pkr.hcl
- pipelines/build-azure-agents-image.yml
- pipelines/infra-cd.yml
- terraform.tfvars
- Added a Scale Set to serve as an Azure DevOps agent pool - Azure DevOps makes changes outside of Terraform when it is set up in an Agent Pool, hence why changes to some attributes are ignored
- Added a VNet for the Scale set to sit in
- Added custom image creation for VM with Packer
> Add Scale Set and Packer custom image for Azure DevOps agents

- infrastructure/network.tf
- pipelines/infra-cd.yml
- pipelines/infra-ci.yml
- Reverts to previous CI/CD pipelines for the deployment of tooling network and self-hosted agents.
> Update VNET address space using managed agents

- README.md
- packer/azure-agents/tools.sh
- pipelines/build-azure-agents-image.yml
- pipelines/infra-cd.yml
- pipelines/infra-ci.yml
- Add the Cypress dependencies to build agent - https://docs.cypress.io/guides/continuous-integration/introduction#Dependencies
- Add .NET Core - https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
- Updated README
> Add .Net Core, and Cypress dependencies to build agents. Updated README file

- pipelines/build-agent-image-cleanup.yml
- pipelines/build-azure-agents-image.yml
- pipelines/infra-cd.yml
- pipelines/infra-ci.yml
- pipelines/purge-acr-images.yml
- Adds a pipeline that runs an `acr purge` command on a schedule
- Created the pipeline here - https://dev.azure.com/planninginspectorate/infrastructure/_build?definitionId=139&_a=summary
> Clean up manifests in Container Registry

- packer/azure-agents/build.pkr.hcl
> updating the packer build script

- README.md
> updating the packer build script init

- infrastructure/azure-devops-agent-pool.tf
- infrastructure/provider.tf
- packer/azure-agents/build.pkr.hcl
> changing azurerm

- infrastructure/key-vault.tf
- pipelines/build-agent-image-cleanup.yml
- pipelines/build-azure-agents-image.yml
- pipelines/infra-cd.yml
- pipelines/purge-acr-images.yml
Use new variable groups and Service Principles for pieplines
> chore: update variable groups and service connections

- infrastructure/dart.tf
https://pins-ds.atlassian.net/browse/DEV-201
Add a storage account + container for DaRT terraform state
> feat: storage account for dart terraform

- infrastructure/appeals-back-office-storage.tf
> creating storage for appeals back office

- infrastructure/appeals-back-office-storage.tf
- infrastructure/container-registry.tf
DEV 177
Added in training container for the new appeals back office service
> Adding in training container

- infrastructure/network.tf
https://pins-ds.atlassian.net/browse/DEV-253
Adding a private DNS zone for internal PINS services
> feat: add pins.internal private DNS zone

- infrastructure/network.tf
https://pins-ds.atlassian.net/browse/DEV-244
- [feat: add privatelink.azuresynapse.net private dns zone](https://github.com/Planning-Inspectorate/infrastructure-tooling/commit/62aec8acf95e9aa192f1ac1fc2e231d7de814650)
- [feat: add privatelink.dfs.core.windows.net private dns zone](https://github.com/Planning-Inspectorate/infrastructure-tooling/commit/2ac3f0e86a7cd996c4dae8acbf70117fa15bf0f9)
- [feat: add privatelink.vaultcore.azure.net private dns zone](https://github.com/Planning-Inspectorate/infrastructure-tooling/commit/bfdc60e4c0732e48f70b93a0faad540704fc5d96)
> feat: add private dns zones

- infrastructure/network.tf
> fix: correct vnet links (copy paste error)

- packer/azure-agents/config.sh
> adding in repos

- infrastructure/provider.tf
> remove tf version

- pipelines/build-agent-image-cleanup.yml
Image clean-up on a schedule stops us creating images separately from deploying them. So this PR removes that schedule.
> fix: don't run agent image cleanup on schedule

- packer/azure-agents/tools.sh
> fix(agent): use a usr/local folder for tfenv install

- packer/azure-agents/tools.sh
> fix(agent): add tfenv to path correctly

- packer/azure-agents/config.sh
> Add zip to common packages for image

- packer/azure-agents/tools.sh
> fix(agent): make tfenv available from /usr/local/bin for agents

- packer/azure-agents/tools.sh
> fix(agent): add tfenv to shell path

- infrastructure/template-app-storage.tf
> feat: add storage account for template app service

- .pre-commit-config.yaml
- infrastructure/template-app-storage.tf
> packer storage account and continer

- infrastructure/data.tf
- infrastructure/rbac.tf
> feat: custom rbac role for blob storage

- infrastructure/rbac.tf
> fix: blob storage actions are data actions

- infrastructure/rbac.tf
> fix: allow rbac role assignment in all odt subs

- infrastructure/network.tf
> changing vnet size

- infrastructure/network.tf
- infrastructure/vpn.tf
> initial commit for vpn implementation, vnet ip range changes

- infrastructure/network.tf
- infrastructure/vpn.tf
> changing subnet naming to GatewaySubnet

- infrastructure/vpn.tf
> adding in values for vpn config

- infrastructure/provider.tf
> chore(tooling): upgrading-tf-to-v-1.9.6

- infrastructure/front-door.tf
- infrastructure/resource-group.tf
> feat(infrastructure): add shared front door instance

- packer/azure-agents/tools.sh
> feat(agent): install Node v22 and bump default to v20

- infrastructure/appeals-back-office-storage.tf
- infrastructure/dart.tf
- infrastructure/network.tf
- infrastructure/template-app-storage.tf
> updating resources for azurerm4

- infrastructure/azure-devops-agent-pool.tf
dev 298
adding in options for the scale sets 
https://registry.terraform.io/providers/hashicorp/azurerm/4.8.0/docs/resources/linux_virtual_machine_scale_set
> Dev 298 scale in settings

- .tflint.hcl
- infrastructure/provider.tf
> Upgrade terraform

- pipelines/purge-acr-images.yml
Avoids tags that resemble a git hash
So that services can use a git hash for the deployed tag version and manage purging themselves
> feat: avoid tags that resemble git hash when purging ACR

- infrastructure/provider.tf
updating azurerm to latest version 3.18.0
[Ticket](https://pins-ds.atlassian.net/browse/DEV-350)
> chore(tooling): updating azurerm version

- packer/azure-agents/tools.sh
updating latest terraform version to create a new image for azure agents
> chore(tooling): updating terraform version to create new image

- infrastructure/data.tf
updating azure agent image name to deploy storage account changes
> fic(infrastructure): updating azure agent image name

- infrastructure/data.tf
> fix(infrastructure): updating azure agent image name

- infrastructure/data.tf
azure-agents-20250219150358 consist of latest terraform version upgrade 
Also deletion of repeated node installations
> fix(infrastructure): update azure agent image

- infrastructure/network.tf
Adding a private DNS zone to support the ODW VPN
https://pins-ds.atlassian.net/browse/DEV-361
> feat(infrastructure): add privatelink.dev.azuresynapse.net private DNS zone

- infrastructure/prototypes-common-infrastructure-storage.tf
Adding storage account for infrastructure prototype repository
> feat(infrastructure): adding storage account for prototype common infrastructure

- infrastructure/network.tf
> feat(infrastructure): add all the storage private dns zones

- infrastructure/provider.tf
Updating AzureRM to latest version 4.26.0 as part of monthly infrastructure updates
terraform latest version is 1.11.3 which is included with in the required condition [">= 1.1.6, < 1.12.0"]
> chore(tooling): upgrading AzureRM version to latest

- packer/azure-agents/build.pkr.hcl
- packer/azure-agents/tools.sh
- pipelines/build-azure-agents-image.yml
- pipelines/infra-cd.yml
Updating agent to latest terraform version 1.11.6 
https://pins-ds.atlassian.net/jira/software/projects/DEV/boards/205?selectedIssue=DEV-385
NOTE:
Updating Infra-cd and image build pipeline to use ubuntu-22.04 azure agent image as with ubuntu-latest(version 24) terraform in not installed by default and pipeline fails with 'terraform command not' found error
> chore(tooling): updating terraform version to latest

- packer/azure-agents/tools.sh
Adding command to install powershell
> chore(tooling): chore(tooling): adding command to install powershell

- infrastructure/data.tf
- packer/azure-agents/tools.sh
Adding PowerShell installation and updating azure agents with newly created image
Task:
https://pins-ds.atlassian.net/jira/software/projects/DEV/boards/205?selectedIssue=DEV-385
https://pins-ds.atlassian.net/browse/DEV-394
> chore(tooling): updating azure agent image with poweshell installation and terraform upgrade

- infrastructure/front-door.tf
Adding terraform configuration to set up new  log analytics and diagnostic setting for shared premium front door 'pins-fd-common-tooling' for non-prod environments 
[<ins>**Ticket**</ins>]( https://pins-ds.atlassian.net/browse/DEV-320)
[**Terraform plan**](https://dev.azure.com/planninginspectorate/infrastructure/_build/results?buildId=111786&view=logs&j=8650e360-1459-5101-e84f-ba4f7168c6eb&t=07426eaf-e965-5952-ed6c-1318353b2fab&l=139)
> feat(tooling): adding log analytics and diagnostic setting for frontdoor

- infrastructure/applications-service-storage.tf
Adding storage account for applictaions app service 
Part of setting up cd pipeline for front door in applications service repository 
Ticket: https://pins-ds.atlassian.net/browse/DEV-462
> feat(tooling): adding storage account for applications service

- pipelines/infra-ci.yml
> ci: always run for infrastructure changes!

- pipelines/build-azure-agents-image.yml
- pipelines/infra-cd.yml
- pipelines/infra-ci.yml
Update pipeline template to support checkov v3 upgrades
https://pins-ds.atlassian.net/browse/DEV-457
> chore: update pipeline templates for checkov upgrades

- infrastructure/data.tf
- infrastructure/provider.tf
- packer/azure-agents/build.pkr.hcl
- packer/azure-agents/tools.sh
> feat: upgrading the agents

- infrastructure/inspector-programming-storage.tf
> chore: adding inspector programming storage account for state file

- infrastructure/scheduling-storage.tf
> chore: changing storage account and container names

- infrastructure/appeals-front-office-storage.tf
Adding staging container for Appeals Front Office
> feat(infrastructure): adding staging container for appeals front office

- infrastructure/provider.tf
> task: upgrade terraform version

- infrastructure/storage-casework-portal.tf
> chore(infrastructure): creating storage account for casework portal terraform state
